//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormChatBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string username { get; set; }
        public string password { get; set; }
        public string fullname { get; set; }
        public Nullable<int> age { get; set; }
        public string gender { get; set; }
        public Nullable<int> phone { get; set; }
        public string size { get; set; }
        public string style { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> administration { get; set; }
    }
}
