//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormChatBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int num { get; set; }
        public string username { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<bool> administration { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
